[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
filehash = true

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = []

[serve]
address = "127.0.0.1"
port = 8080

[clean]
dist = "dist"
cargo = false

[tools]
wasm_bindgen = "0.2.84"
wasm_opt = "version_111"